### PR TITLE
Follow symlinks when building env from files.

### LINKED ISSUE #526: Directories are being picked up in `/platform/env` as files
### Summary
<!--- Please provide a general summary of the issue. -->
Detector is failing to load the `/platform/env` due to a symlink to a directory.

### Reproduction

##### Steps
<!--- What steps should be taken to reproduce the issue? -->

1. Create `..data` symlink to `..a_dir` directory in `/platform/env`
2. Run detector
3. See failure referencing `..data` 

##### Current behavior
<!--- What happened? Logs, etc. could go here. -->
It looks as though lifecycle is reading `..data` as a file and not ignoring it as a directory. By default, directories are ignored by the platform env loading seen [here](https://github.com/buildpacks/lifecycle/blob/ca47d3defd627d7ebb16e5e3b98bb9cc9b2d7ca4/env/env.go#L164).

```
===> DETECTING                                                                                                                                                                                                         │
│ ERROR: failed to read full env: read /platform/env/..data: is a directory
```

##### Expected
<!--- What did you expect to happen? -->
I expect detector to succeed in loading the platform env, ignoring the `..data` symlink to the directory.

---

### Context

##### lifecycle version
<!--- If you can find this, it helps us pin down the issue. For example, run `pack inspect-builder BUILDER` which should report the lifecycle version in question. -->
`0.10.1+36da170`

##### anything else?
<!--- Tekton task version, kpack version, etc. -->
This is in kubernetes and I found it by mounting an entire secret without using subpaths. When you do not use subpaths when mounting a configmap or secret, you get symlinks so that kubernetes can keep the file up to date. If you use subpaths, the symlink will not be present and it works as expected. See [here](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod) and [here](https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically)

### PR DESCRIPTION
**Pull request by jabrown85**
Symlinks to directories should be evaluated so they can be skipped when building env.

Fixes #526

### CODE REVIEW

**Comment by jabrown85** [comment]
TODO: Rebase once https://github.com/buildpacks/lifecycle/pull/528 or similar is merged

**Review by natalieparellano — APPROVED** [review]

**Comment by jabrown85** [comment]
Rebased on `main` to fix CI failures

File: env/env.go [hunk 1]
```diff
@@ -164,6 +164,19 @@ func eachEnvFile(dir string, fn func(k, v string) error) error {
...
 		}
+		if f.Mode()&os.ModeSymlink != 0 {
+			lnPath, err := filepath.EvalSymlinks(filepath.Join(dir, f.Name()))
+			if err != nil {
+				return err
+			}
+			lnFile, err := os.Stat(lnPath)
+			if err != nil {
+				return err
+			}
```
Comment (ekcasey) [inline env/env.go:175]:
```suggestion
			lnFile, err := os.Stat(filepath.Join(dir, f.Name()))
			if err != nil {
				return err
			}
```

`os.Stat` already stats the link target (`os.Lstat` would stat the link) so there is no need to evalulate the links first.

**Review by ekcasey — APPROVED** [review]
